// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/bubble/v1/bubble.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type CreateBubbleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBubbleRequest) Reset() {
	*x = CreateBubbleRequest{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBubbleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBubbleRequest) ProtoMessage() {}

func (x *CreateBubbleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBubbleRequest.ProtoReflect.Descriptor instead.
func (*CreateBubbleRequest) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBubbleRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateBubbleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBubbleReply) Reset() {
	*x = CreateBubbleReply{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBubbleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBubbleReply) ProtoMessage() {}

func (x *CreateBubbleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBubbleReply.ProtoReflect.Descriptor instead.
func (*CreateBubbleReply) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBubbleReply) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateBubbleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBubbleRequest) Reset() {
	*x = UpdateBubbleRequest{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBubbleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBubbleRequest) ProtoMessage() {}

func (x *UpdateBubbleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBubbleRequest.ProtoReflect.Descriptor instead.
func (*UpdateBubbleRequest) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBubbleRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateBubbleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBubbleReply) Reset() {
	*x = UpdateBubbleReply{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBubbleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBubbleReply) ProtoMessage() {}

func (x *UpdateBubbleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBubbleReply.ProtoReflect.Descriptor instead.
func (*UpdateBubbleReply) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBubbleReply) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteBubbleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBubbleRequest) Reset() {
	*x = DeleteBubbleRequest{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBubbleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBubbleRequest) ProtoMessage() {}

func (x *DeleteBubbleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBubbleRequest.ProtoReflect.Descriptor instead.
func (*DeleteBubbleRequest) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBubbleRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// 获取所有事件不需要传参
// message ListBubbleRequest {}
type ListBubbleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBubbleReply) Reset() {
	*x = ListBubbleReply{}
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBubbleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBubbleReply) ProtoMessage() {}

func (x *ListBubbleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bubble_v1_bubble_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBubbleReply.ProtoReflect.Descriptor instead.
func (*ListBubbleReply) Descriptor() ([]byte, []int) {
	return file_api_bubble_v1_bubble_proto_rawDescGZIP(), []int{6}
}

func (x *ListBubbleReply) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_bubble_v1_bubble_proto protoreflect.FileDescriptor

const file_api_bubble_v1_bubble_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/bubble/v1/bubble.proto\x12\rapi.bubble.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"A\n" +
	"\x13CreateBubbleRequest\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.api.bubble.v1.EventR\x05event\"?\n" +
	"\x11CreateBubbleReply\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.api.bubble.v1.EventR\x05event\"A\n" +
	"\x13UpdateBubbleRequest\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.api.bubble.v1.EventR\x05event\"?\n" +
	"\x11UpdateBubbleReply\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.api.bubble.v1.EventR\x05event\"A\n" +
	"\x13DeleteBubbleRequest\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.api.bubble.v1.EventR\x05event\"?\n" +
	"\x0fListBubbleReply\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.api.bubble.v1.EventR\x06events2\xb7\x03\n" +
	"\x06Bubble\x12n\n" +
	"\fCreateBubble\x12\".api.bubble.v1.CreateBubbleRequest\x1a .api.bubble.v1.CreateBubbleReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x05event\"\tv1/create\x12n\n" +
	"\fUpdateBubble\x12\".api.bubble.v1.UpdateBubbleRequest\x1a .api.bubble.v1.UpdateBubbleReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x05event\x1a\tv1/update\x12h\n" +
	"\fDeleteBubble\x12\".api.bubble.v1.DeleteBubbleRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14v1/delete/{event.id}\x12c\n" +
	"\n" +
	"ListBubble\x12\x16.google.protobuf.Empty\x1a\x1e.api.bubble.v1.ListBubbleReply\"\x1d\x82\xd3\xe4\x93\x02\x17Z\f:\x01*\"\av1/list\x12\av1/listB*\n" +
	"\rapi.bubble.v1P\x01Z\x17bubble/api/bubble/v1;v1b\x06proto3"

var (
	file_api_bubble_v1_bubble_proto_rawDescOnce sync.Once
	file_api_bubble_v1_bubble_proto_rawDescData []byte
)

func file_api_bubble_v1_bubble_proto_rawDescGZIP() []byte {
	file_api_bubble_v1_bubble_proto_rawDescOnce.Do(func() {
		file_api_bubble_v1_bubble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bubble_v1_bubble_proto_rawDesc), len(file_api_bubble_v1_bubble_proto_rawDesc)))
	})
	return file_api_bubble_v1_bubble_proto_rawDescData
}

var file_api_bubble_v1_bubble_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_bubble_v1_bubble_proto_goTypes = []any{
	(*Event)(nil),               // 0: api.bubble.v1.Event
	(*CreateBubbleRequest)(nil), // 1: api.bubble.v1.CreateBubbleRequest
	(*CreateBubbleReply)(nil),   // 2: api.bubble.v1.CreateBubbleReply
	(*UpdateBubbleRequest)(nil), // 3: api.bubble.v1.UpdateBubbleRequest
	(*UpdateBubbleReply)(nil),   // 4: api.bubble.v1.UpdateBubbleReply
	(*DeleteBubbleRequest)(nil), // 5: api.bubble.v1.DeleteBubbleRequest
	(*ListBubbleReply)(nil),     // 6: api.bubble.v1.ListBubbleReply
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_api_bubble_v1_bubble_proto_depIdxs = []int32{
	0,  // 0: api.bubble.v1.CreateBubbleRequest.event:type_name -> api.bubble.v1.Event
	0,  // 1: api.bubble.v1.CreateBubbleReply.event:type_name -> api.bubble.v1.Event
	0,  // 2: api.bubble.v1.UpdateBubbleRequest.event:type_name -> api.bubble.v1.Event
	0,  // 3: api.bubble.v1.UpdateBubbleReply.event:type_name -> api.bubble.v1.Event
	0,  // 4: api.bubble.v1.DeleteBubbleRequest.event:type_name -> api.bubble.v1.Event
	0,  // 5: api.bubble.v1.ListBubbleReply.events:type_name -> api.bubble.v1.Event
	1,  // 6: api.bubble.v1.Bubble.CreateBubble:input_type -> api.bubble.v1.CreateBubbleRequest
	3,  // 7: api.bubble.v1.Bubble.UpdateBubble:input_type -> api.bubble.v1.UpdateBubbleRequest
	5,  // 8: api.bubble.v1.Bubble.DeleteBubble:input_type -> api.bubble.v1.DeleteBubbleRequest
	7,  // 9: api.bubble.v1.Bubble.ListBubble:input_type -> google.protobuf.Empty
	2,  // 10: api.bubble.v1.Bubble.CreateBubble:output_type -> api.bubble.v1.CreateBubbleReply
	4,  // 11: api.bubble.v1.Bubble.UpdateBubble:output_type -> api.bubble.v1.UpdateBubbleReply
	7,  // 12: api.bubble.v1.Bubble.DeleteBubble:output_type -> google.protobuf.Empty
	6,  // 13: api.bubble.v1.Bubble.ListBubble:output_type -> api.bubble.v1.ListBubbleReply
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_bubble_v1_bubble_proto_init() }
func file_api_bubble_v1_bubble_proto_init() {
	if File_api_bubble_v1_bubble_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bubble_v1_bubble_proto_rawDesc), len(file_api_bubble_v1_bubble_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bubble_v1_bubble_proto_goTypes,
		DependencyIndexes: file_api_bubble_v1_bubble_proto_depIdxs,
		MessageInfos:      file_api_bubble_v1_bubble_proto_msgTypes,
	}.Build()
	File_api_bubble_v1_bubble_proto = out.File
	file_api_bubble_v1_bubble_proto_goTypes = nil
	file_api_bubble_v1_bubble_proto_depIdxs = nil
}
