// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/bubble/v1/bubble.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBubbleCreateBubble = "/api.bubble.v1.Bubble/CreateBubble"
const OperationBubbleDeleteBubble = "/api.bubble.v1.Bubble/DeleteBubble"
const OperationBubbleListBubble = "/api.bubble.v1.Bubble/ListBubble"
const OperationBubbleUpdateBubble = "/api.bubble.v1.Bubble/UpdateBubble"

type BubbleHTTPServer interface {
	CreateBubble(context.Context, *CreateBubbleRequest) (*CreateBubbleReply, error)
	DeleteBubble(context.Context, *DeleteBubbleRequest) (*emptypb.Empty, error)
	// ListBubble rpc GetBubble (GetBubbleRequest) returns (GetBubbleReply);
	ListBubble(context.Context, *emptypb.Empty) (*ListBubbleReply, error)
	UpdateBubble(context.Context, *UpdateBubbleRequest) (*UpdateBubbleReply, error)
}

func RegisterBubbleHTTPServer(s *http.Server, srv BubbleHTTPServer) {
	r := s.Route("/")
	r.POST("v1/create", _Bubble_CreateBubble0_HTTP_Handler(srv))
	r.PUT("v1/update", _Bubble_UpdateBubble0_HTTP_Handler(srv))
	r.DELETE("v1/delete/{event.id}", _Bubble_DeleteBubble0_HTTP_Handler(srv))
	r.POST("v1/list", _Bubble_ListBubble0_HTTP_Handler(srv))
	r.GET("v1/list", _Bubble_ListBubble1_HTTP_Handler(srv))
}

func _Bubble_CreateBubble0_HTTP_Handler(srv BubbleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBubbleRequest
		if err := ctx.Bind(&in.Event); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBubbleCreateBubble)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBubble(ctx, req.(*CreateBubbleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBubbleReply)
		return ctx.Result(200, reply)
	}
}

func _Bubble_UpdateBubble0_HTTP_Handler(srv BubbleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBubbleRequest
		if err := ctx.Bind(&in.Event); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBubbleUpdateBubble)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBubble(ctx, req.(*UpdateBubbleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateBubbleReply)
		return ctx.Result(200, reply)
	}
}

func _Bubble_DeleteBubble0_HTTP_Handler(srv BubbleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBubbleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBubbleDeleteBubble)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBubble(ctx, req.(*DeleteBubbleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Bubble_ListBubble0_HTTP_Handler(srv BubbleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBubbleListBubble)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBubble(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBubbleReply)
		return ctx.Result(200, reply)
	}
}

func _Bubble_ListBubble1_HTTP_Handler(srv BubbleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBubbleListBubble)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBubble(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBubbleReply)
		return ctx.Result(200, reply)
	}
}

type BubbleHTTPClient interface {
	CreateBubble(ctx context.Context, req *CreateBubbleRequest, opts ...http.CallOption) (rsp *CreateBubbleReply, err error)
	DeleteBubble(ctx context.Context, req *DeleteBubbleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ListBubble rpc GetBubble (GetBubbleRequest) returns (GetBubbleReply);
	ListBubble(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListBubbleReply, err error)
	UpdateBubble(ctx context.Context, req *UpdateBubbleRequest, opts ...http.CallOption) (rsp *UpdateBubbleReply, err error)
}

type BubbleHTTPClientImpl struct {
	cc *http.Client
}

func NewBubbleHTTPClient(client *http.Client) BubbleHTTPClient {
	return &BubbleHTTPClientImpl{client}
}

func (c *BubbleHTTPClientImpl) CreateBubble(ctx context.Context, in *CreateBubbleRequest, opts ...http.CallOption) (*CreateBubbleReply, error) {
	var out CreateBubbleReply
	pattern := "v1/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBubbleCreateBubble))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Event, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BubbleHTTPClientImpl) DeleteBubble(ctx context.Context, in *DeleteBubbleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "v1/delete/{event.id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBubbleDeleteBubble))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBubble rpc GetBubble (GetBubbleRequest) returns (GetBubbleReply);
func (c *BubbleHTTPClientImpl) ListBubble(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListBubbleReply, error) {
	var out ListBubbleReply
	pattern := "v1/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBubbleListBubble))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BubbleHTTPClientImpl) UpdateBubble(ctx context.Context, in *UpdateBubbleRequest, opts ...http.CallOption) (*UpdateBubbleReply, error) {
	var out UpdateBubbleReply
	pattern := "v1/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBubbleUpdateBubble))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Event, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
