// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/bubble/v1/bubble.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bubble_CreateBubble_FullMethodName = "/api.bubble.v1.Bubble/CreateBubble"
	Bubble_UpdateBubble_FullMethodName = "/api.bubble.v1.Bubble/UpdateBubble"
	Bubble_DeleteBubble_FullMethodName = "/api.bubble.v1.Bubble/DeleteBubble"
	Bubble_ListBubble_FullMethodName   = "/api.bubble.v1.Bubble/ListBubble"
)

// BubbleClient is the client API for Bubble service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BubbleClient interface {
	CreateBubble(ctx context.Context, in *CreateBubbleRequest, opts ...grpc.CallOption) (*CreateBubbleReply, error)
	UpdateBubble(ctx context.Context, in *UpdateBubbleRequest, opts ...grpc.CallOption) (*UpdateBubbleReply, error)
	DeleteBubble(ctx context.Context, in *DeleteBubbleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// rpc GetBubble (GetBubbleRequest) returns (GetBubbleReply);
	ListBubble(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBubbleReply, error)
}

type bubbleClient struct {
	cc grpc.ClientConnInterface
}

func NewBubbleClient(cc grpc.ClientConnInterface) BubbleClient {
	return &bubbleClient{cc}
}

func (c *bubbleClient) CreateBubble(ctx context.Context, in *CreateBubbleRequest, opts ...grpc.CallOption) (*CreateBubbleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBubbleReply)
	err := c.cc.Invoke(ctx, Bubble_CreateBubble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bubbleClient) UpdateBubble(ctx context.Context, in *UpdateBubbleRequest, opts ...grpc.CallOption) (*UpdateBubbleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBubbleReply)
	err := c.cc.Invoke(ctx, Bubble_UpdateBubble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bubbleClient) DeleteBubble(ctx context.Context, in *DeleteBubbleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Bubble_DeleteBubble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bubbleClient) ListBubble(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBubbleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBubbleReply)
	err := c.cc.Invoke(ctx, Bubble_ListBubble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BubbleServer is the server API for Bubble service.
// All implementations must embed UnimplementedBubbleServer
// for forward compatibility.
type BubbleServer interface {
	CreateBubble(context.Context, *CreateBubbleRequest) (*CreateBubbleReply, error)
	UpdateBubble(context.Context, *UpdateBubbleRequest) (*UpdateBubbleReply, error)
	DeleteBubble(context.Context, *DeleteBubbleRequest) (*emptypb.Empty, error)
	// rpc GetBubble (GetBubbleRequest) returns (GetBubbleReply);
	ListBubble(context.Context, *emptypb.Empty) (*ListBubbleReply, error)
	mustEmbedUnimplementedBubbleServer()
}

// UnimplementedBubbleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBubbleServer struct{}

func (UnimplementedBubbleServer) CreateBubble(context.Context, *CreateBubbleRequest) (*CreateBubbleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBubble not implemented")
}
func (UnimplementedBubbleServer) UpdateBubble(context.Context, *UpdateBubbleRequest) (*UpdateBubbleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBubble not implemented")
}
func (UnimplementedBubbleServer) DeleteBubble(context.Context, *DeleteBubbleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBubble not implemented")
}
func (UnimplementedBubbleServer) ListBubble(context.Context, *emptypb.Empty) (*ListBubbleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBubble not implemented")
}
func (UnimplementedBubbleServer) mustEmbedUnimplementedBubbleServer() {}
func (UnimplementedBubbleServer) testEmbeddedByValue()                {}

// UnsafeBubbleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BubbleServer will
// result in compilation errors.
type UnsafeBubbleServer interface {
	mustEmbedUnimplementedBubbleServer()
}

func RegisterBubbleServer(s grpc.ServiceRegistrar, srv BubbleServer) {
	// If the following call panics, it indicates UnimplementedBubbleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bubble_ServiceDesc, srv)
}

func _Bubble_CreateBubble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBubbleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BubbleServer).CreateBubble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bubble_CreateBubble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BubbleServer).CreateBubble(ctx, req.(*CreateBubbleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bubble_UpdateBubble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBubbleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BubbleServer).UpdateBubble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bubble_UpdateBubble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BubbleServer).UpdateBubble(ctx, req.(*UpdateBubbleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bubble_DeleteBubble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBubbleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BubbleServer).DeleteBubble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bubble_DeleteBubble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BubbleServer).DeleteBubble(ctx, req.(*DeleteBubbleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bubble_ListBubble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BubbleServer).ListBubble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bubble_ListBubble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BubbleServer).ListBubble(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Bubble_ServiceDesc is the grpc.ServiceDesc for Bubble service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bubble_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bubble.v1.Bubble",
	HandlerType: (*BubbleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBubble",
			Handler:    _Bubble_CreateBubble_Handler,
		},
		{
			MethodName: "UpdateBubble",
			Handler:    _Bubble_UpdateBubble_Handler,
		},
		{
			MethodName: "DeleteBubble",
			Handler:    _Bubble_DeleteBubble_Handler,
		},
		{
			MethodName: "ListBubble",
			Handler:    _Bubble_ListBubble_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bubble/v1/bubble.proto",
}
